---

- block:
  - name: get OS codename
    command: sed -n 's/^VERSION.*(\(.*\)).*/\1/p' /etc/os-release
    register: cn

  - name: set OS codename fact
    set_fact:
      ansible_lsb: "{{ {'codename': cn.stdout } }}"
  when: ansible_lsb is undefined

- name: add GPG keys for repositories
  apt_key: url={{ item }} state=present
  with_items: "{{ svc.providers.pkg.repositories.values() | map(attribute='keys') | sum(start=[]) | unique | list }}"
  when: ansible_pkg_mgr == "apt"
  become: true


- name: add repositories
  apt_repository: repo="deb {{ item }}"
                  filename="{{ svc.name }}"
                  state=present
  with_items: "{{ svc.providers.pkg.repositories.values() | map(attribute='url') | unique | list }}"
  when: ansible_pkg_mgr == "apt"
  become: true
